//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Müşteri
    {
        public int Müsteri_Id { get; set; }
        public string Müsteri_Ad { get; set; }
        public int Bilet_Sayısı { get; set; }
        public string Bilet_Aralıgı { get; set; }
        public int Film_Id { get; set; }
        public int Salon_Id { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
